#!/usr/bin/env python3
"""
Generate SpektraGeneratedTranslations.h from translations.json.

Usage:
    python generate_translations.py \
        --input Resources/lang/translations.json \
        --output path/to/SpektraGeneratedTranslations.h
"""

import argparse
import json
import os
import sys


LANG_MAP = [
    ("en",    "EN"),
    ("zh-CN", "ZH_CN"),
    ("zh-TW", "ZH_TW"),
    ("ja",    "JA"),
    ("ko",    "KO"),
]


def generate_header(input_path, output_path):
    with open(input_path, "r", encoding="utf-8") as f:
        source = json.load(f)

    lines = [
        "// Auto-generated by generate_translations.py — do not edit.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <cstring>",
        "",
        "namespace spektrafilm {",
        "",
        "enum class Language : uint8_t {",
    ]

    for lang_key, lang_enum in LANG_MAP:
        prefix = "  " if lang_enum == "EN" else "  "
        comma = "," if lang_enum != LANG_MAP[-1][1] else ","
        lines.append(f"{prefix}{lang_enum} = {LANG_MAP.index((lang_key, lang_enum))}{comma}")

    lines.append("};")
    lines.append("")

    lines.append("struct TranslationEntry {")
    lines.append("  const char *id;")
    lines.append("  const char *text;")
    lines.append("};")
    lines.append("")

    table_names = []
    for lang_key, lang_enum in LANG_MAP:
        data = source.get(lang_key, {})
        items = sorted(data.items())
        table_name = f"kTranslations{lang_enum}"
        table_names.append((table_name, lang_enum))
        table_count_name = f"{table_name}Count"

        lines.append(f"inline const TranslationEntry {table_name}[] = {{")
        for string_id, text in items:
            escaped_id = string_id.replace("\\", "\\\\").replace('"', '\\"')
            escaped_text = text.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'  {{"{escaped_id}", "{escaped_text}"}},')
        lines.append("};")
        lines.append("")
        lines.append(f"inline constexpr int {table_count_name} =")
        lines.append(f"  static_cast<int>(sizeof({table_name}) / sizeof({table_name}[0]));")
        lines.append("")

    # lookup helper
    lines.append("inline const char *lookupTranslation(")
    lines.append("  const TranslationEntry *table, int count, const char *id) {")
    lines.append("  int lo = 0, hi = count - 1;")
    lines.append("  while (lo <= hi) {")
    lines.append("    int mid = (lo + hi) / 2;")
    lines.append("    int cmp = std::strcmp(table[mid].id, id);")
    lines.append("    if (cmp == 0) return table[mid].text;")
    lines.append("    if (cmp < 0) lo = mid + 1;")
    lines.append("    else hi = mid - 1;")
    lines.append("  }")
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")

    # language variable and init
    lines.append("inline Language &currentLanguageRef() {")
    lines.append("  static Language lang = Language::EN;")
    lines.append("  return lang;")
    lines.append("}")
    lines.append("")

    lines.append("inline void initLanguage(Language lang) {")
    lines.append("  currentLanguageRef() = lang;")
    lines.append("}")
    lines.append("")

    lines.append("inline Language currentLanguage() {")
    lines.append("  return currentLanguageRef();")
    lines.append("}")
    lines.append("")

    # main translate function
    lines.append("inline const char *tr(const char *id) {")
    lines.append("  const TranslationEntry *table = nullptr;")
    lines.append("  int count = 0;")
    lines.append("  switch (currentLanguageRef()) {")

    for table_name, lang_enum in table_names:
        lines.append(f"    case Language::{lang_enum}:")
        lines.append(f"      table = {table_name};")
        lines.append(f"      count = {table_name}Count;")
        lines.append("      break;")

    lines.append("    default:")
    lines.append("      break;")
    lines.append("  }")
    lines.append("")
    lines.append("  if (table) {")
    lines.append("    const char *result = lookupTranslation(table, count, id);")
    lines.append("    if (result) return result;")
    lines.append("  }")
    lines.append("")
    lines.append("  const char *fallback = lookupTranslation(")
    lines.append("    kTranslationsEN, kTranslationsENCount, id);")
    lines.append("  return fallback ? fallback : id;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace spektrafilm")
    lines.append("")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {output_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Path to translations.json")
    parser.add_argument("--output", required=True, help="Path to output .h file")
    args = parser.parse_args()
    generate_header(args.input, args.output)


if __name__ == "__main__":
    main()
